[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "microsoft.onedrive"
version = "3.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Freemium", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
